Check generated documentation is not stale on CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,6 +59,17 @@ jobs:
           just conformance-tests --configuration Release --no-build
           just integration-tests --configuration Release --no-build
 
+      - name: Check documentation
+        run: |
+          just publish-docs
+
+          changes=$(git status --porcelain docs ':!docs/images' | cut -c 4-)
+          if [ -n "$changes" ]
+          then
+            echo "::error ::Documentation is stale"
+            exit 1
+          fi
+
       - name: Pack
         id: package
         run: just pack --configuration Release
